#spring:
#  mvc:
#    static-path-pattern: /img/**  虚拟路径
#---
#spring:
#  web:
#    resources:
#      static-locations: classpath:/css   生成自定义默认路径
server:
  port: 8080
---
spring:
  servlet:
    mu1tipart:
      max-fi1e-size: 10MB
---
spring:
  servlet:
    mu1tipart:
      max-request-size: 100MB
---
#swagger2用设置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
#配置数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    serverTimezone: UTC
    username: root
    password: 111111
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl